export { remove } from './utilities/remove'
export { select } from './utilities/select'
export { splitPathAtLastKey } from './utilities/splitPathAtLastKey'
export { spread } from './utilities/spread'
export { set } from './utilities/set'
export { updateImmutably, updateImmutablyAllowingNewProps } from './utilities/updateImmutably'
export { DotPaths, DotPathsIncludingLength, UpdateDotPathObject, ValueInDotPath, UpdateDotPathValue } from './types'